name: CI/CD Pipeline for Kubernetes Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2  # Set the region for all AWS actions

    # Login to Amazon ECR
    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    # Build and push Docker image to ECR
    - name: Build and push Docker image
      run: |
        docker build -t 590183982448.dkr.ecr.us-west-2.amazonaws.com/my-python-r-image:${{ github.sha }} .
        docker push 590183982448.dkr.ecr.us-west-2.amazonaws.com/my-python-r-image:${{ github.sha }}

    # Update Kubernetes deployment
    - name: Update Kubernetes deployment
      run: |
        aws eks update-kubeconfig --name my-python-r-cluster # Replace <Your-Cluster-Name> with your actual cluster name
        kubectl set image deployment/myapp-deployment myapp=590183982448.dkr.ecr.us-west-2.amazonaws.com/my-python-r-image:${{ github.sha }} --record
        kubectl rollout status deployment/myapp-deployment

   
    # Update Kubernetes deployment
    - name: Deploy to Kubernetes
      run: |
        kubectl set image deployment/myapp-deployment myapp=590183982448.dkr.ecr.us-west-2.amazonaws.com/my-python-r-image:${{ github.sha }} --record
        kubectl rollout status deployment/myapp-deployment
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
